import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "./Sidebar/SideMenu";
import Topbar from "./Topbar/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Startups",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideMenu />
        <Topbar />
        {children}
      </body>
    </html>
  );
}
